/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import br.senai.sp.jandira.model.PlanoDeSaude;
import javax.swing.JOptionPane;

/**
 *
 * @author 22282094
 */
public class PlanoDeSaudeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form PlanoDeSaudeJDialog
     */
    public PlanoDeSaudeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelNomeDaOperadora = new javax.swing.JLabel();
        jTextFieldNomeDaOperadora = new javax.swing.JTextField();
        jLabelTituloDoPlano = new javax.swing.JLabel();
        jTextFieldTipoDoPlano = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(757, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro Planos De Saude");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 300, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar48px.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 48, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 60);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do Plano de Saúde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setLayout(null);

        jLabelCodigo.setText("Código");
        jPanel2.add(jLabelCodigo);
        jLabelCodigo.setBounds(20, 50, 80, 16);

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(20, 70, 60, 22);

        jLabelNomeDaOperadora.setText("Nome Da Operadora");
        jPanel2.add(jLabelNomeDaOperadora);
        jLabelNomeDaOperadora.setBounds(20, 110, 200, 16);
        jPanel2.add(jTextFieldNomeDaOperadora);
        jTextFieldNomeDaOperadora.setBounds(20, 130, 290, 22);

        jLabelTituloDoPlano.setText("Tipo Do Plano");
        jPanel2.add(jLabelTituloDoPlano);
        jLabelTituloDoPlano.setBounds(20, 170, 240, 16);
        jPanel2.add(jTextFieldTipoDoPlano);
        jTextFieldTipoDoPlano.setBounds(20, 190, 290, 22);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/delete48px.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jPanel2.add(jButtonCancelar);
        jButtonCancelar.setBounds(440, 230, 60, 60);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/save32.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar);
        jButtonSalvar.setBounds(360, 230, 60, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 530, 300);

        setBounds(0, 0, 569, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        //criar Objeto Plano de Saude
        
        PlanoDeSaude planoDeSaude = new PlanoDeSaude();
        planoDeSaude.setOperadora(jTextFieldNomeDaOperadora.getText());
        planoDeSaude.setTipoDoPlano(jTextFieldTipoDoPlano.getText());
        
        if(validarCAdastro())
        {PlanoDeSaudeDAO.gravar(planoDeSaude);
        JOptionPane.showMessageDialog(this,  
                "Plano de Saúde gravado com sucesso", 
                "Plano De Saude",
                JOptionPane.INFORMATION_MESSAGE);
        dispose();}
        
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    
    private boolean validarCAdastro(){
     if (jTextFieldNomeDaOperadora.getText().isEmpty()) {
    
         JOptionPane.showMessageDialog(this, "Digite o nome da Operadora", "ERRO", JOptionPane.ERROR_MESSAGE);
          jTextFieldNomeDaOperadora.requestFocus();
         return false; 
        
     }
     if (jTextFieldTipoDoPlano.getText().isEmpty()){
     JOptionPane.showMessageDialog(this, "Digite o nome da Operadora", "ERRO", JOptionPane.ERROR_MESSAGE);
         jTextFieldTipoDoPlano.requestFocus();
     return false;   
     }
     return true;
    }    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanoDeSaudeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanoDeSaudeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanoDeSaudeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanoDeSaudeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlanoDeSaudeJDialog dialog = new PlanoDeSaudeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelNomeDaOperadora;
    private javax.swing.JLabel jLabelTituloDoPlano;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomeDaOperadora;
    private javax.swing.JTextField jTextFieldTipoDoPlano;
    // End of variables declaration//GEN-END:variables
}
