package br.senai.sp.jandira.model;

public enum Estados {

	
	SAO_PAULO,MINAS_GERAIS,RIO_DE_JANEIRO,ESPIRITO_SANTO,
	RIO_GRANDE_DO_SUL,SANTA_CATARINA,PARANA,AMAZPNAS,
	ACRE,RORAIMA,PARA,RONDONIA,AMAPA,
	
}
